name: Call a reusable workflows

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      - name: Local Action Call
        id: local-action
        uses: ./.github/actions/reusable
        with:
          name: "World"
