name: Call a reusable workflows

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4 # Necessaryy to access local action
      - name: Local Action Call
        id: local-action
        uses: ./.github/actions/reusable
        with:
          name: "World"
