name: Call a reusable workflows

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: reusable/.github/workflows/reusable.yml@main
    with:
      username: mona
