name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: maheshworks/reusable-workflow/.github/workflows/reusable.yml@main
    with:
      username: mona
